/*Question #1: 
What is the average annual revenue per sector of clients 
that work in the sectors Insurance and Banking?*/


SELECT
    -- Clean up sector names by standardizing them to a consistent format
    CASE 
        WHEN LOWER(sector) = 'consumer goods' THEN 'Consumer Goods'
        WHEN LOWER(sector) = 'insurance' THEN 'Insurance'
        WHEN LOWER(sector) = 'banking' THEN 'Banking'
        WHEN LOWER(sector) = 'retail' THEN 'Retail'
        ELSE sector  -- If none of the conditions match, keep the original sector value
    END AS cleaned_sector,
    
    AVG(annual_revenue)  -- Calculate the average annual revenue for each cleaned sector

FROM meta_clients

-- Filter the rows where sector contains either 'insurance' or 'banking', case-insensitive
WHERE REGEXP_LIKE(sector, 'insurance|banking', 'i')

-- Group the results by the cleaned sector names
GROUP BY 1;  -- Grouping by the first column, which is cleaned_sector

 
------ OR

SELECT
    LOWER(sector) AS sector,  -- Convert the sector to lowercase for consistent grouping
    AVG(annual_revenue)       -- Calculate the average annual revenue for each sector

FROM 
    meta_clients

WHERE 
    LOWER(sector) IN ('banking', 'insurance')  -- Filter rows where sector is either 'banking' or 'insurance' (case-insensitive)

GROUP BY 1  -- Group by the first column (sector)
;



/*Question #2: 
Your manager wants to analyze the marketing spend percentage by country, 
but the data is not 100% clean. He mentions that you can clean the country 
field by using the sales team information, and shared the following mapping with you: 

UK = United Kingdom
FR = France
ES = Spain
IT = Italy
DACH = Germany

What is the average marketing spend percentage per country?*/
SELECT
    CASE
        -- Standardize sales_team values to country names based on patterns
        WHEN sales_team LIKE ('%UK%') THEN 'United Kingdom'  -- If 'UK' appears in sales_team, label it 'United Kingdom'
        WHEN sales_team LIKE ('%FR%') THEN 'France'          -- If 'FR' appears, label it 'France'
        WHEN sales_team LIKE ('%ES%') THEN 'Spain'           -- If 'ES' appears, label it 'Spain'
        WHEN sales_team LIKE ('%IT%') THEN 'Italy'           -- If 'IT' appears, label it 'Italy'
        WHEN sales_team LIKE ('%DACH%') THEN 'Germany'       -- If 'DACH' appears, label it 'Germany'
        ELSE country  -- If none of the patterns match, keep the original country value
    END AS clean_country,

    -- Calculate the average marketing spend percentage for each country
    AVG(marketing_spend_perc) AS total_marketing_spend_perc
    
FROM 
    meta_clients

-- Group by the clean_country name (derived from the CASE statement)
GROUP BY 1;  -- Group by the first column (clean_country)



-----OR

SELECT
    CASE
        -- Use COALESCE to check country first, and if it's NULL, fallback to sales_team
        -- Standardize the resulting value into a country name based on patterns
        WHEN COALESCE(country, sales_team) LIKE ('%UK%') THEN 'United Kingdom'  -- If 'UK' appears in country or sales_team
        WHEN COALESCE(country, sales_team) LIKE ('%FR%') THEN 'France'          -- If 'FR' appears
        WHEN COALESCE(country, sales_team) LIKE ('%ES%') THEN 'Spain'           -- If 'ES' appears
        WHEN COALESCE(country, sales_team) LIKE ('%IT%') THEN 'Italy'           -- If 'IT' appears
        WHEN COALESCE(country, sales_team) LIKE ('%DACH%') THEN 'Germany'       -- If 'DACH' appears
        ELSE country  -- If none of the patterns match, keep the original country value
    END AS clean_country,

    -- Calculate the average marketing spend percentage for each country
    AVG(marketing_spend_perc) AS total_marketing_spend_perc
    
FROM 
    meta_clients

-- Group by the cleaned country name derived from the CASE statement
GROUP BY 1;  -- Group by the first column (clean_country)


/*Question #3: 
The data seems to be much cleaner now! Your manager is interested in comparing
the revenue generated by Meta against the total marketing spend of the clients.

What is the total marketing spend in $
(annual revenue of the client multiplied by marketing spend %)
and the total revenue generated by Meta per client ID in 2022 for 
the cleaned up country values Spain and Italy?

You can reuse the cleaned up country logic from question 2.*/

SELECT 
    SUBSTRING(c.client_id, 8) AS client_id,  -- Extract part of the client_id from position 8
    MAX(c.annual_revenue) * MAX(c.marketing_spend_perc) AS total_marketing_spend,  -- Calculate marketing spend based on max revenue and percentage
    SUM(r.revenue) AS total_revenue  -- Sum the revenue from the meta_revenue table

FROM 
    meta_clients AS c
JOIN 
    meta_revenue AS r
ON 
    c.client_id = r.client_id

WHERE 
    EXTRACT(YEAR FROM r.dates) = 2022  -- Filter for the year 2022
    AND (CASE
           WHEN c.sales_team LIKE ('%UK%') THEN 'United Kingdom' 
           WHEN c.sales_team LIKE ('%FR%') THEN 'France'
           WHEN c.sales_team LIKE ('%ES%') THEN 'Spain'
           WHEN c.sales_team LIKE ('%IT%') THEN 'Italy'
           WHEN c.sales_team LIKE ('%DACH%') THEN 'Germany' 
           ELSE c.country
         END) IN ('Spain', 'Italy')  -- Check for 'Spain' or 'Italy' based on sales_team or country

GROUP BY 
    1;  -- Group by the extracted client_id


----- OR 

WITH sub AS (
  -- Clean the country names based on sales_team and fallback to country if no match
  SELECT
      client_id,
      CASE 
          WHEN sales_team LIKE '%UK%' THEN 'United Kingdom'
          WHEN sales_team LIKE '%FR%' THEN 'France'
          WHEN sales_team LIKE '%ES%' THEN 'Spain'
          WHEN sales_team LIKE '%IT%' THEN 'Italy'
          WHEN sales_team LIKE '%DACH%' THEN 'Germany'
          ELSE country 
      END AS country_cleaned,
      annual_revenue,
      marketing_spend_perc
  FROM meta_clients
)

SELECT 
    sub.client_id,  -- Return client_id
    MAX(sub.annual_revenue) * MAX(sub.marketing_spend_perc) AS total_client_marketing_spend,  -- Calculate total marketing spend
    COALESCE(SUM(mr.revenue), 0) AS total_revenue  -- Sum revenue, replacing NULL with 0
FROM sub 
LEFT JOIN meta_revenue mr 
    ON sub.client_id = mr.client_id  -- Left join with meta_revenue to capture clients without revenue
WHERE 
    sub.country_cleaned IN ('Spain', 'Italy')  -- Filter for Spain and Italy
    AND EXTRACT(YEAR FROM mr.dates) = 2022  -- Filter for the year 2022
GROUP BY 
    sub.client_id  -- Group by client_id
;


/*Question #4:
Create a client list and calculate the customer penetration % 
for clients in 2022 with an industry that matches consumer goods.

The customer penetration can be calculated as follows:
Meta revenue generated in one year divided by the marketing spend $ (from question 3)

Show the clients with the lowest customer penetration first.*/

SELECT 
    c.client_id,  -- Selecting the client_id from the meta_clients table
    SUM(r.revenue) / (MAX(c.annual_revenue) * MAX(c.marketing_spend_perc)) AS penetration  -- Calculating penetration by dividing total revenue by max annual revenue times max marketing spend percentage for each client

FROM 
    meta_clients AS c  -- Alias for the meta_clients table
JOIN 
    meta_revenue AS r  -- Alias for the meta_revenue table
ON 
    c.client_id = r.client_id  -- Joining meta_clients with meta_revenue based on client_id

WHERE
    EXTRACT(YEAR FROM r.dates) = 2022  -- Filtering the revenue data for the year 2022
    AND REGEXP_LIKE(c.industry, 'consumer goods', 'i')  -- Filtering clients whose industry matches 'consumer goods' (case-insensitive)

GROUP BY 
    1  -- Grouping by the first column (client_id)
ORDER BY 
    2 ASC  -- Ordering the results by the second column (penetration) in ascending order
  ;


--- OR 

SELECT 
    c.client_id,  -- Selecting the client_id from the meta_clients table
    SUM(r.revenue) / (MAX(c.annual_revenue) * MAX(c.marketing_spend_perc)) AS customer_penetration  -- Calculating customer penetration by dividing total revenue by max annual revenue times max marketing spend percentage

FROM 
    meta_clients AS c  -- Alias for the meta_clients table
JOIN 
    meta_revenue AS r  -- Alias for the meta_revenue table
ON 
    c.client_id = r.client_id  -- Joining meta_clients with meta_revenue based on client_id

WHERE
    EXTRACT(YEAR FROM r.dates) = 2022  -- Filtering the revenue data for the year 2022
    AND LOWER(c.industry) LIKE ('%consumer goods%')  -- Filtering clients where the industry contains 'consumer goods', case-insensitive

GROUP BY 
    1  -- Grouping by the first column (client_id)
ORDER BY 
    2 ASC;  -- Ordering the results by the second column (customer_penetration) in ascending order
    
/*Question #5: 
Reuse the answer of question 4.

Clean up the industry data and calculate the customer penetration for
the clients in the Retail & Consumer Goods industries based on the Meta revenue data from 2022?

The following values should fall under Retail & Consumer Goods: 
retail, Retail, Consumer Goods, RCG, Retail & Consumer Goods. */

SELECT 
    c.client_id,  
    SUM(r.revenue) / (MAX(c.annual_revenue) * MAX(c.marketing_spend_perc)) AS customer_penetration  -- Calculate customer penetration by dividing total revenue by max annual revenue and max marketing spend percentage

FROM 
    meta_clients AS c
JOIN 
    meta_revenue AS r
ON 
    c.client_id = r.client_id  -- Join meta_clients with meta_revenue on client_id

WHERE
    EXTRACT(YEAR FROM r.dates) = 2022  -- Filter data for the year 2022
    AND REGEXP_LIKE(c.industry, 'consumer goods|retail|rcg', 'i')  -- Case-insensitive pattern match to filter industries (consumer goods, retail, or rcg)

GROUP BY 
    1  -- Group by client_id
;


--- OR 

SELECT 
    clients.client_id,  
    SUM(revenue.revenue) / (MAX(clients.marketing_spend_perc) * MAX(clients.annual_revenue)) AS customer_penetration  -- Calculate customer penetration by dividing total revenue by the product of max marketing spend percentage and max annual revenue

FROM 
    meta_revenue revenue
INNER JOIN 
    meta_clients clients ON revenue.client_id = clients.client_id  -- Join meta_revenue and meta_clients on client_id

WHERE 
    EXTRACT(YEAR FROM dates) = 2022  -- Filter for the year 2022
    AND CASE 
        WHEN UPPER(clients.industry) LIKE '%CONSUMER GOODS%' THEN 'Retail & Consumer Goods'  -- Standardize industry to 'Retail & Consumer Goods' for consumer goods
        WHEN UPPER(clients.industry) LIKE '%RETAIL%' THEN 'Retail & Consumer Goods'         -- Standardize industry to 'Retail & Consumer Goods' for retail
        WHEN clients.industry = 'RCG' THEN 'Retail & Consumer Goods'                        -- Standardize for 'RCG'
        ELSE industry                                                                      -- Otherwise, keep original industry
    END = 'Retail & Consumer Goods'  -- Filter for 'Retail & Consumer Goods' industry

GROUP BY 
    clients.client_id  -- Group by client_id
;

/*Question #6: 
Finally, your manager is interested in understanding how the customer penetration % 
of our biggest clients has changed year over year based on the changes 
in the revenue generated by Meta.

We can assume that the annual revenue of the client remains consistent.

Calculate the customer penetration % for every available year that
we have Meta revenue available for for the client ID “Client_1010”*/

SELECT 
    EXTRACT(YEAR FROM r.dates) AS year,  -- Extract the year from the 'dates' column in the 'meta_revenue' table
    SUM(r.revenue) / (MAX(c.annual_revenue) * MAX(c.marketing_spend_perc)) AS penetration  -- Calculate penetration by dividing total revenue by the product of max annual revenue and max marketing spend percentage

FROM 
    meta_clients AS c
JOIN 
    meta_revenue AS r ON c.client_id = r.client_id  -- Join 'meta_clients' and 'meta_revenue' on 'client_id'

WHERE 
    c.client_id = 'Client_1010'  -- Filter for a specific client with 'client_id' = 'Client_1010'

GROUP BY 
    1  -- Group by the extracted year (first column in the SELECT list)
;
